import streamlit as st
import pandas as pd
import math
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from fpdf import FPDF
import io

# ==============================================================================
# 1. CLASS & FUNGSI UNTUK GENERATE PDF
# ==============================================================================
class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 14)
        self.cell(0, 10, 'LAPORAN PERHITUNGAN STABILITAS BENDUNG', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Generated by Sistem Desain Irigasi Terpadu', 0, 1, 'C')
        self.line(10, 30, 200, 30)
        self.ln(10)

    def chapter_title(self, label):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 10, label, 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, text):
        self.set_font('Arial', '', 11)
        self.multi_cell(0, 7, text)
        self.ln()

def create_pdf(inputs, results):
    pdf = PDFReport()
    pdf.add_page()
    
    # Bagian 1: Data Input
    pdf.chapter_title('1. PARAMETER DESAIN')
    text_input = (
        f"Kondisi Tinjauan: {inputs['kondisi']}\n"
        f"Lebar Dasar (B): {inputs['B']} m\n"
        f"Sudut Geser (Phi): {inputs['phi']} deg\n"
        f"Kohesi (c): {inputs['c']} t/m2\n"
        f"Berat Jenis Tanah: {inputs['gamma']} t/m3"
    )
    pdf.chapter_body(text_input)

    # Bagian 2: Gaya-Gaya
    pdf.chapter_title('2. REKAPITULASI GAYA')
    text_gaya = (
        f"Total Momen Penahan (Mt): {inputs['Mt']} tm\n"
        f"Total Momen Guling (Mg): {inputs['Mg']} tm\n"
        f"Total Gaya Vertikal Efektif: {results['V_eff']:.2f} ton\n"
        f"Total Gaya Horizontal: {inputs['H']} ton"
    )
    pdf.chapter_body(text_gaya)

    # Bagian 3: Hasil Analisis
    pdf.chapter_title('3. HASIL ANALISIS KEAMANAN (SAFETY FACTOR)')
    
    # Logika Status
    stat_guling = "AMAN" if results['SF_guling'] >= 1.5 else "TIDAK AMAN"
    stat_geser = "AMAN" if results['SF_geser'] >= 1.5 else "TIDAK AMAN"
    stat_e = "AMAN" if results['e'] <= inputs['B']/6 else "WARNING"
    stat_dd = "AMAN" if results['sigma_max'] <= results['sigma_ijin'] else "BAHAYA"

    text_hasil = (
        f"A. GULING (Overturning)\n"
        f"   SF Guling = {results['SF_guling']:.2f} (Syarat >= 1.5) -> {stat_guling}\n\n"
        f"B. GESER (Sliding)\n"
        f"   SF Geser  = {results['SF_geser']:.2f} (Syarat >= 1.5) -> {stat_geser}\n\n"
        f"C. EKSENTRISITAS\n"
        f"   Nilai e   = {results['e']:.3f} m (Batas {inputs['B']/6:.3f} m) -> {stat_e}\n\n"
        f"D. DAYA DUKUNG TANAH\n"
        f"   Tegangan Ijin = {results['sigma_ijin']:.2f} t/m2\n"
        f"   Tegangan Max  = {results['sigma_max']:.2f} t/m2 -> {stat_dd}"
    )
    pdf.chapter_body(text_hasil)
    
    pdf.ln(10)
    pdf.set_font('Arial', 'I', 10)
    pdf.cell(0, 10, '(Akhir Laporan)', 0, 1, 'C')
    
    return pdf.output(dest="S").encode("latin-1")

# ==============================================================================
# 2. KONFIGURASI HALAMAN STREAMLIT
# ==============================================================================
st.set_page_config(page_title="Analisis Stabilitas Bendung Pro", layout="wide")

st.title("🛡️ Analisis Stabilitas Bendung (Plus Visualisasi & PDF)")
st.markdown("---")

# --- SIDEBAR INPUT ---
with st.sidebar:
    st.header("1. Input Parameter")
    B = st.number_input("Lebar Dasar (B) [m]", value=1.30, step=0.1)
    Df = st.number_input("Kedalaman Pondasi (Df) [m]", value=3.0, step=0.5)
    st.markdown("---")
    st.caption("Parameter Tanah")
    gamma_tanah = st.number_input("Berat Jenis Tanah (t/m3)", value=1.813)
    phi = st.number_input("Sudut Geser (deg)", value=42.5)
    c = st.number_input("Kohesi (c) [t/m2]", value=0.142)
    st.caption("Faktor Terzaghi")
    Nc = st.number_input("Nc", value=95.0)
    Nq = st.number_input("Nq", value=90.0)
    Ngamma = st.number_input("Ngamma", value=160.0)

# --- MAIN INPUT (GAYA) ---
col_main1, col_main2 = st.columns([1, 2])

with col_main1:
    st.subheader("2. Input Gaya")
    kondisi = st.radio("Kondisi:", ["M.A.N (Normal)", "M.A.B (Banjir)"])
    
    # Default values logic
    if kondisi == "M.A.N (Normal)":
        d_Vt, d_Va, d_H, d_Mt, d_Mg = 36.37, 4.19, 10.28, 65.76, 41.77
    else:
        d_Vt, d_Va, d_H, d_Mt, d_Mg = 40.47, 10.38, 7.69, 99.94, 61.68

    V_tahan = st.number_input("ΣV Tahan [ton]", value=d_Vt)
    V_angkat = st.number_input("ΣV Uplift [ton]", value=d_Va)
    H_dorong = st.number_input("ΣH Dorong [ton]", value=d_H)
    M_tahan = st.number_input("Σ Momen Tahan [tm]", value=d_Mt)
    M_guling = st.number_input("Σ Momen Guling [tm]", value=d_Mg)

# ==============================================================================
# 3. PROSES HITUNGAN
# ==============================================================================
# Hitungan Dasar
V_eff = V_tahan - V_angkat
M_net = M_tahan - M_guling

# A. Guling
sf_guling = M_tahan / M_guling if M_guling != 0 else 0

# B. Geser
tan_phi = math.tan(math.radians(phi))
Gaya_Gesek = (V_eff * tan_phi) + (c * B)
sf_geser = Gaya_Gesek / H_dorong if H_dorong != 0 else 0

# C. Eksentrisitas
try:
    e = abs((M_net / V_eff) - (B / 2))
except:
    e = 0
batas_e = B / 6

# D. Daya Dukung
B_eff = B - (2 * e)
term_c = c * Nc
term_q = gamma_tanah * Df * (Nq - 1)
term_gamma = 0.5 * gamma_tanah * B_eff * Ngamma
q_ult = term_c + term_q + term_gamma

FS_tanah = 3.0 if kondisi == "M.A.N (Normal)" else 2.5
sigma_ijin = q_ult / FS_tanah
sigma_max = (V_eff / B) * (1 + (6 * e / B))

# Simpan hasil dalam dictionary untuk PDF
inputs_dict = {
    'kondisi': kondisi, 'B': B, 'phi': phi, 'c': c, 'gamma': gamma_tanah,
    'Mt': M_tahan, 'Mg': M_guling, 'H': H_dorong
}
results_dict = {
    'V_eff': V_eff, 'SF_guling': sf_guling, 'SF_geser': sf_geser,
    'e': e, 'sigma_max': sigma_max, 'sigma_ijin': sigma_ijin
}

# ==============================================================================
# 4. TAMPILAN OUTPUT & VISUALISASI
# ==============================================================================
with col_main2:
    st.subheader("3. Dashboard Analisis")
    
    # --- TAB VISUALISASI ---
    tab_angka, tab_grafik = st.tabs(["📊 Angka Detail", "📈 Visualisasi Grafik"])
    
    with tab_angka:
        c1, c2, c3 = st.columns(3)
        c1.metric("SF Guling", f"{sf_guling:.2f}", delta="Min 1.5", delta_color="normal")
        c2.metric("SF Geser", f"{sf_geser:.2f}", delta="Min 1.5", delta_color="normal")
        c3.metric("Eksentrisitas (e)", f"{e:.3f} m", delta=f"Max {batas_e:.3f}", delta_color="inverse")
        
        st.write(f"**Daya Dukung:** {sigma_max:.2f} t/m2 (Ijin: {sigma_ijin:.2f} t/m2)")
        if sigma_max <= sigma_ijin:
            st.success("STATUS: AMAN")
        else:
            st.error("STATUS: TIDAK AMAN")

    with tab_grafik:
        col_graf1, col_graf2 = st.columns(2)
        
        # Grafik 1: Bar Chart SF Guling
        with col_graf1:
            st.caption("Perbandingan Momen")
            fig1, ax1 = plt.subplots(figsize=(4, 3))
            colors = ['#ff9999', '#66b3ff']
            ax1.bar(['Guling', 'Tahan'], [M_guling, M_tahan], color=colors)
            ax1.set_ylabel('Momen (tm)')
            ax1.set_title(f'SF Guling = {sf_guling:.2f}')
            st.pyplot(fig1)

        # Grafik 2: Visualisasi Eksentrisitas pada Tapak
        with col_graf2:
            st.caption("Posisi Resultan Gaya (Inti)")
            fig2, ax2 = plt.subplots(figsize=(4, 3))
            
            # Gambar Tapak Pondasi (Rectangle)
            rect = patches.Rectangle((0, 0), B, 1, linewidth=2, edgecolor='black', facecolor='none')
            ax2.add_patch(rect)
            
            # Garis Tengah
            ax2.axvline(x=B/2, color='gray', linestyle='--')
            
            # Zona Inti (Kern) - Hijau Transparan
            kern_start = (B/2) - (B/6)
            kern_end = (B/2) + (B/6)
            ax2.axvspan(kern_start, kern_end, alpha=0.3, color='green', label='Zona Inti (B/6)')
            
            # Posisi Resultan Gaya (Titik Merah)
            # e dihitung dari pusat, jadi posisi absolut = B/2 +/- e
            # Asumsi momen netto positif arah jarum jam (kanan)
            posisi_resultan = (B/2) + e 
            ax2.plot(posisi_resultan, 0.5, 'ro', markersize=10, label='Resultan Gaya')
            
            ax2.set_xlim(-0.5, B+0.5)
            ax2.set_ylim(0, 1.2)
            ax2.set_yticks([])
            ax2.set_xlabel('Lebar Bendung (m)')
            ax2.legend(loc='upper right', fontsize='small')
            st.pyplot(fig2)

# ==============================================================================
# 5. TOMBOL DOWNLOAD PDF
# ==============================================================================
st.markdown("---")
col_d, col_info = st.columns([1, 4])

with col_d:
    pdf_bytes = create_pdf(inputs_dict, results_dict)
    st.download_button(
        label="📄 Download Laporan PDF",
        data=pdf_bytes,
        file_name="Laporan_Stabilitas_Bendung.pdf",
        mime="application/pdf",
    )

with col_info:
    st.info("Klik tombol di kiri untuk mengunduh Laporan Perhitungan resmi siap cetak.")